<?php $this->headTitle()->append('Nutzungsbedingungen') ?>

<div style="text-align:left; font-size:90%; width:90%; margin-left:5%;">

<h2> Nutzungsbedingungen </h2> 

<p>Letzte Änderung am <?php echo date('d. M Y', $this->modified) ?>.</p>

<p>Durch die Verwendung von <a href="http://<?php echo $this->url ?>"><?php echo $this->url ?></a> erklären Sie, dass Sie die Nutzungsbedingungen gelesen haben, verstehen und erklären sich mit diesen Bestimmungen und Bedingungen einverstanden. </p> 

<p> <?php echo $this->sitename ?> behält sich das Recht vor, ein beliebiges Bild aus irgendeinem Grund zu entfernen. Insbesondere jedes hochgeladene Bild, welches pornografisch oder anstößig (einschließlich der Nacktheit, Gewalt, sexuelle Handlungen oder sexuell provokante Bilder) ist, gegen das Urheberrecht verstößt welche nicht durch den Uploader gehalten werden, rechtswidrig oder gegen Gesetze ist, wird sofort gelöscht. Ein Verstoß gegen diese Bedingungen resultiert in der Beendigung der Möglichkeit, weitere Bilder hochzuladen. </p> 

<p> Wir behalten uns das Recht vor, jeden einzelnen Uploader die Nutzung unserer Services aus irgendeinem Grund zu verbieten. </p> 

<p> Wir können für etwaige Schäden nicht haftbar gemacht werden. Alle Daten, Fotos, Nachrichten, Grafiken, Kommentare, Texte, Tags oder sonstige Materialien ("Inhalt"), liegen in der alleinigen Verantwortung der Person, von der diese Inhalte stammen. Sie, und nicht <?php echo $this->sitename ?>, haben die gesamte Verantwortung für alle Inhalte, die Sie eingeben, veröffentlichen, per E-Mail versenden, übermitteln oder anderweitig durch <?php echo $this->sitename ?> verfügbar machen. <?php echo $this->sitename ?> kontrolliert nicht die Inhalte und übernimmt keine Garantie für die Richtigkeit oder Vollständigkeit dieser Inhalte. </p> 

<p> <?php echo $this->sitename ?> haftet nicht für irgendwelche Aussagen oder Verhaltensweisen Dritter die bei der Nutzung dieses Dienstes entstehen. Durch die Verwendung von <?php echo $this->sitename ?> können Sie einem Inhalt ausgesetzt werden, den Sie unanständig, anstößig oder beleidigend empfinden. </p> 

<p> <?php echo $this->sitename ?> ist in keiner Weise für den Inhalt, einschließlich der Haftung, aber nicht beschränkt auf etwaige Fehler oder Auslassungen im Content, verantwortlich. <?php echo $this->sitename ?> kann nicht für irgendwelche Verluste oder Schäden die auf irgendwelcher Art als Folge der Nutzung von Inhalten gebucht, per E-Mail versendet, übermittelt oder auf andere Weise entstehen, zur Verfügung gestellt auf <?php echo $this->sitename ?> haftbar gemacht werden. <?php echo $this->sitename ?> übernimmt keinerlei Gewähr für die Aktualität, Löschung, miss-Lieferung oder Nichterfüllung eines Benutzer-Content, Kommunikation oder persönliche Einstellungen zu speichern. </p> 

<p> Sie erklären sich damit einverstanden und halten <?php echo $this->sitename ?>, seine Angestellten und Mitarbeiter frei von jeglichen Ansprüchen oder Forderungen, einschließlich angemessener Anwaltskosten, die von Dritten aufgrund oder aus Inhalten, die Sie übermitteln, übertragen, veröffentlichen oder anderweitig über <?php echo $this->sitename ?> verfügbar machen. </p> 

<h4>Tarife</h4>
<p>Datenblätter sind öffentlich auf den Seiten der Printmedien zugänglich und wurden dort entnommen.</p>

<h4>Auswertungen</h4>
<p>Statistiken stellen einen unvollständigen Sachverhalt dar. Es kann keine Garantie gegeben werden für die Richtigkeit und Vollständigkeit der Angaben.</p>

<h4>Abbildungen und Artikel</h4>
<p>Alle Abbildungen und Artikel die auf der fotografierten Seite dargestellt werden stehen in keinem Zusammenhang mit dem Inserat und den entsprechenden Zuordnungen.</p>

<!--<h4> Wahl der Gerichtsbarkeit </h4> 

<p> Die Nutzungsbedingungen und die Beziehung zwischen Ihnen und <?php echo $this->sitename ?> unterliegen den Gesetzen des Staates Österreich, ohne Hinweis auf seine Vorschriften des Internationalen Privatrechts geregelt. Sie und <?php echo $this->sitename ?> erklären sich mit der persönlichen und ausschließlichen Zuständigkeit der Gerichte in Wien, Österreich einverstanden. </p> -->

<h4> Copyright </h4> 

<p> Durch das Hochladen Ihres Fotos auf <?php echo $this->sitename ?> geben Sie <?php echo $this->sitename ?> die Erlaubnis, Ihre Fotos auf <?php echo $this->url ?> zu verwenden.</p> 

<p>
<a rel="license" href="http://creativecommons.org/licenses/by/3.0/at/"><img alt="Creative Commons Lizenzvertrag" style="border-width:0" src="http://i.creativecommons.org/l/by/3.0/88x31.png" /></a><br /><span xmlns:dc="http://purl.org/dc/elements/1.1/" href="http://purl.org/dc/dcmitype/StillImage" property="dc:title" rel="dc:type">Der Inhalt</span> von <a xmlns:cc="http://creativecommons.org/ns#" href="http://<?php echo $this->url ?>" property="cc:attributionName" rel="cc:attributionURL"><?php echo $this->sitename ?></a> steht unter einer <a rel="license" href="http://creativecommons.org/licenses/by/3.0/at/">Creative Commons Attribution 3.0 Austria Lizenz</a>.<br />Beruht auf einem Inhalt unter <a xmlns:dc="http://purl.org/dc/elements/1.1/" href="http://<?php echo $this->url ?>" rel="dc:source">http://<?php echo $this->url ?></a>.
</p>

<p> Alle hochgeladenen Bilder sind urheberrechtlich geschützt © bei ihren jeweiligen Eigentümern </p> 

<!--

<h2>Copyright</h2>
Code gibt es derzeit nur bei Nachfrage. <br />
Code ist derzeit in Vorbeitung zur Veröffentlichung auf Github unter einer Open Source Lizenz.<br /><br />

<ul style="text-align:left;">
<li>Programmcode -> GPL</li>
<li>Fotos von Twitpic & Co</li>
</ul>

-->

</div>