<?php $this->headTitle()->append('Impressum') ?>
<h2>Impressum</h2>
<h3 style="text-align:center;">Programmierer</h3>
Gerold Neuwirt<br />
Kreuzgasse 81<br />
1180 Wien<br />
<a href="http://twitter.com/gemane">Twitter</a><br />
<br />
<h3 style="text-align:center;">Idee</h3>
Georg Holzer<br />
<a href="http://www.k2020.at/2010/04/15/inserate-in-die-datenbank/">http://www.k2020.at/</a><br />
<br />
<h3 style="text-align:center;">Usability</h3>
<a href="http://twitter.com/hofrat">Clemens Schuster</a><br />
<br />
<h3 style="text-align:center;">Smartphone Apps</h3>
iPhone: Martin Gratzer<br />
<a href="http://www.topmind.at/">http://www.topmind.at/</a><br />
<br />
Android: Bruno Hautzenberger<br />
<a href="http://www.the-engine.at/">http://www.the-engine.at/</a><br />
<br />
Zuletzt editiert: <?php echo date('d. M Y H:i:s', $this->lastEdited) ?><br />
