<?php 
$this->headTitle()->append('überprüfung der Eingabe');
?>
<?php echo $this->partial('partials/input/partial_navigation.phtml', $this->navigation) ?>
<?php if ($this->tagged) : ?>
<h2 style="clear:left;">Inserat wurde bereits zugeordnet</h2>
<p>Änderung der zuordnenden Person mehr möglich.</p>
<?php else : ?>
<h2 style="clear:left;">Überprüfung der Eingaben</h2>
<?php endif ?>
<?php if (!empty($this->message)) : ?>
<span class="errors"><?php   print_r($this->message) ?></span>
<br />
<?php endif ?>
<?php if ($this->max_entries && !$this->tagged) : ?>
<?php   if (false != $this->inserat) : ?>
<ul class="inserat">
    <li>Werbung für: <?php echo $this->inserat[0]['party'] ?> (<?php echo $this->inserat[0]['region_party'] ?>)</li>
    <li>Bezahlt von: <?php echo $this->inserat[0]['payer'] ?></li>
    <li>Printmedium: <?php echo $this->inserat[0]['printmedium'] ?> (<?php echo $this->inserat[0]['region_printmedium_bit'] ?>) - <?php echo $this->formatDate($this->inserat[0]['print_date']) ?></li>
    <li>Kategorie: <?php if (1 == $this->inserat[0]['cover']) : ?>Titelblatt / <?php endif ?><?php echo $this->inserat[0]['printmedium_type_name'] ?></li>
    <li>Format: <?php if (1 < $this->inserat[0]['pages']) echo $this->inserat[0]['pages'] . ' x ' ?><?php echo $this->inserat[0]['size'] ?> / <?php echo $this->inserat[0]['size_width'] . ' x ' . $this->inserat[0]['size_height'] ?>mm (b x h)</li>
    <li><strong><?php echo $this->formatCurrency($this->inserat[0]['price_inserat']) ?></strong></li>
    <li>&nbsp;</li>
    <li>Hochgeladen von: <?php echo $this->inserat[0]['uploader'] ?></li>
    <li><span class="errors">Getagged von: <?php echo $this->inserat[0]['tagger'] ?></span></li>
    <li>Quelle: <?php echo $this->inserat[0]['source'] ?></li>
    <li><?php echo $this->formatTime($this->inserat[0]['timestamp']) ?></li>
</ul>
<?php   endif ?>
<?php   if (empty($this->message) && !$this->tagged) : ?>
<?php       echo $this->formFixer($this->form) ?>
<?php   endif ?>
<div style="clear:both;">
    <img src="<?php echo $this->image['image'] ?>" width="<?php echo $this->image['width'] ?>" height="<?php echo $this->image['height'] ?>" border="1" alt="Inserat" />
</div>
<?php endif ?>
