<?php 
$this->headTitle()->append('Tarife');
$this->showTooltips();
?>

<h3>
<?php if ($this->csv) : ?>
<div style="text-align:left;" class="tagspan" title="CSV der Tarife herunterladen"><a href="/tarife/exportcsv/">Download Tarife</a></div>
<?php endif ?>
<?php if ($this->auth) :?>
<div style="text-align:right;" class="tagspan_link" title="Daten editieren"><a href="/tarife/edit/medium/<?php echo $this->id_medium ?>">editieren &raquo;</a></div>
<?php endif ?>
</h3>
<h2>Anzeigentarife in den Printmedien</h2>
<?php if ($this->advertisments) : ?> <!-- TODO3 Weitere Werbewege -->
<div style="display:inline;" class="tagspan_link_inactive" title="Inserate">Inserate</div>
<div style="display:inline;" class="tagspan_link" title="Inserate"><a href="/online">Online-Werbung</a></div>
<div style="display:inline;" class="tagspan_link" title="Plakate"><a href="/plakate">Plakate</a></div>
<div style="display:inline;" class="tagspan_link" title="Postwurfe"><a href="/postwurf">Postwurf</a></div>
<div style="display:inline;" class="tagspan_link" title="Werbegeschenke"><a href="/werbegeschenke">Werbegeschenke</a></div>
<br /><br />
<?php endif ?>
<?php if (!empty($this->table)) : ?>
<div style="clear:both; text-align:left;">
<?php $this->tabContainer()->captureStart('mainTabContainer', array('style'=>'width:100%;', 'doLayout' => 'false')); ?>
<?php foreach ($this->table['printmedien'] as $medium) : ?>
<?php $contentPaneOptions = ($medium['id_printmedium'] == $this->id_medium) ? array('title' => $medium['printmedium'], 'selected' => 'true') : array('title' => $medium['printmedium']) ?>

<?php   $this->contentPane()->captureStart('medium' . $medium['id_printmedium'], array(), $contentPaneOptions) ?>

    <div style="text-align:center;">
    <br />
    <h2><?php echo $medium['printmedium'] ?></h2>
<?php   if (!empty($this->table['types'][$medium['id_printmedium']]) ) : ?>
    <table class="table_types" cellpadding="5" summary="Formate des Printmediums">
<?php echo $this->partialLoop('partials/tariff/partial_types.phtml', $this->table['types'][$medium['id_printmedium']]);?>
    </table>
  <?php endif ?>
<?php   if (empty($medium['keywords_printmedium'])) : ?>
    <span style="font-size:14px;margin-top:0px;margin-bottom:15px;">&nbsp;</span>
<?php   else : ?>
    <span style="font-size:14px;margin-top:0px;margin-bottom:15px;">Alias: "<?php echo $medium['keywords_printmedium'] ?>"</span>
<?php   endif ?>
    <div style="background-color: #852806;padding:5px;margin:0px 20px 20px;"></div>
<?php   if (empty($this->table[$medium['id_printmedium']])) : ?>
        <div style="clear:both; padding-bottom:20px;" ><span class="errors">Kein Datenfile vorhanden.</span></div>
<?php   else : ?>
<?php       foreach ($this->table['datafiles'][$medium['id_printmedium']] as $datafile) : ?>
        <div style="display:inline"><?php echo $datafile['region_printmedium_bit'] ?> (<?php echo $this->escape($datafile['year']) ?>) </div>
        &nbsp;<div style="display:inline" class="tagspan" title="Tarifblatt herunterladen"><a href="/tarife/download/<?php echo $datafile['year'] ?>/<?php echo $this->preparePath($datafile['printmedium']) ?>/<?php echo $datafile['path'] ?>">Download</a></div>
        <div style="font-size: 90%; font-style:italic;margin:5px;"><?php echo $this->formatDate($datafile['date_from']) . ' - ' . $this->formatDate($datafile['date_to']) ?></div>
        <table class="table_tariff" cellpadding="5" summary="Tarife der Anzeigen">
            <tr>
                <th>Bezeichnung</th>
                <th>Breite</th>
                <th>Höhe</th>
                <th>Titelblatt</th>
                <th>Format</th>
                <th>Wochentage</th>
                <th>Preis</th>
            </tr>
<?php           if (empty($this->table[$medium['id_printmedium']][$datafile['id_datafile']]) ) : ?>
            <tr>
                <td colspan="7"><span class="errors">Daten müssen noch eingetragen werden.</span></td>
            </tr>
<?php           else : ?>
<?php               echo $this->partialLoop('partials/tariff/partial_tariff.phtml', $this->table[$medium['id_printmedium']][$datafile['id_datafile']]);
                endif ?>
        </table>
        <br />
<?php       endforeach ?>
<?php   endif ?>
    </div>
<?php   echo $this->contentPane()->captureEnd('medium' . $medium['id_printmedium']); ?>

<?php endforeach ?>
<?php echo $this->tabContainer()->captureEnd('mainTabContainer') ?>
</div>
<?php else : ?>
<span class="errors">Kein Einträge vorhanden.</span>
<br />
<?php endif ?>
<?php if (!$this->auth) :?>
<span class="errors" style="text-align:center;font-size:16px;">Um neue Printmedien hinzuzufügen bzw. vorhandene <br />zu korrigieren müssen Sie sich <a href="/user/login">einloggen</a>.</span>
<?php endif ?>
