<script type="text/javascript" defer="defer" src="/js/intern/plot_front.js"></script>
<script type="text/javascript">
    //<![CDATA[
<?php
echo $this->dataPaymentsMedium . "\n" .
                                  $this->dataColorsMedium . "\n" .
                                  $this->dataLegendMedium . "\n" .
                                  $this->dataLabelMedium . "\n" .
                                  $this->yaxis . "\n"
?>
    //]]>
</script>

<div id="chartParty" style="width:300px; height:170px;"></div>
