<?php 
$this->headTitle()->append('Verlauf der untauglichen Inserate');
/***********************************************
* Image w/ description tooltip v2.0- (c) Dynamic Drive DHTML code library (www.dynamicdrive.com)
* This notice MUST stay intact for legal use
* Visit Dynamic Drive at http://www.dynamicdrive.com/ for this script and 100s more
***********************************************/
$this->headScript()->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js', 'text/javascript', array('defer' => 'defer'));
$this->headScript()->appendScript($this->table['tooltips'])
                   ->appendFile('/js/intern/ddimgtooltip.js', 'text/javascript', array('defer' => 'defer'));
$this->headScript()->appendScript('
function loeschen(objLink, strHREF){
    if(confirm("Wollen Sie das Inserat wirklich löschen?")){
        objLink.href = strHREF;
    }
}
');
?>
<div style="display:inline;" class="tagspan_link" title="Zugeordnete Inserate"><a href="/stream/tagged">Zugeordnet</a></div>
<div style="display:inline;" class="tagspan_link" title="Nicht zugeordnete Inserate"><a href="/stream/untagged">Nicht zugeordnet</a></div>
<div style="display:inline;" class="tagspan_link_inactive" title="Unbrauchbare Inserate">Unbrauchbar</div>
<br /><br />
<h2>Unbrauchbare Inserate</h2>
<span class="errors" style="font-size:14px;clear:both;">Inserate in diesem Ordner werden nach 30 Tagen automatisch vom Server gelöscht.</span>
<table class="table_stream" cellpadding="2" summary="Verlauf der untauglichen Inserate">
    <tr>
<?php if (!empty($this->table['ids'])) : ?>
<?php   foreach ($this->table['ids'] as $id) : ?>
        <td>
<?php echo $this->partialLoop('partials/stream/partial_trashed.phtml', $this->table[$id]) ?>
        </td>
<?php       if ($this->num_column == $this->column++) : ?>
    </tr>
    <tr>
<?php       $this->column = 1 ?>
<?php       endif ?>
<?php   endforeach ?>
<?php else : ?>
        <td>
            <br />
            <h3><span class="errors">Keine Inserate vorhanden.</span></h3>
            <br />
            [<a href="/">zurück</a>]
        </td>
<?php endif ?>
    </tr>
</table>