<div class="statistik">
    <table class="table_statistik" cellpadding="3" summary="Zahlungen der Parteien">
        <tr>
            <th class="label_party">Partei</th>
            <th class="label_party">Zahlender</th>
            <th class="label">Gesamt</th>
            <th class="label">Jan</th>
            <th class="label">Febr</th>
            <th class="label">März</th>
            <th class="label">Apr</th>
            <th class="label">Mai</th>
            <th class="label">Juni</th>
            <th class="label">Juli</th>
            <th class="label">Aug</th>
            <th class="label">Sept</th>
            <th class="label">Okt</th>
            <th class="label">Nov</th>
            <th class="label">Dez</th>
        </tr>
<?php foreach ($this->table['parties'] as $party) : ?>
        <tr>
            <td class="label_party" rowspan="2"><?php echo $party['party'] ?></td>
            <td class="label_party"><?php echo 'Partei' ?></td>
            <td class="label"><?php $this->formatCurrency($this->table[$party['id_config']]['all']['party_payed'], Zend_Currency::NO_SYMBOL) ?>.-</td>
<?php   for ($month = 1; $month <= 12; $month++) : ?>
            <td class="label"><?php $this->formatCurrency($this->table[$party['id_config']][$month]['party_payed'], Zend_Currency::NO_SYMBOL) ?>.-</td>
<?php   endfor ?>
        </tr>
        <tr>
            <td class="label_party"><?php echo 'Regierung' ?></td>
            <td class="label"><?php $this->formatCurrency($this->table[$party['id_config']]['all']['government_payed'], Zend_Currency::NO_SYMBOL) ?>.-</td>
<?php   for ($month = 1; $month <= 12; $month++) : ?>
            <td class="label"><?php $this->formatCurrency($this->table[$party['id_config']][$month]['government_payed'], Zend_Currency::NO_SYMBOL) ?>.-</td>
<?php   endfor ?>
        </tr>
<?php endforeach ?>
    </table>
</div>
Ausgaben in EUR. Nur zugeordnete Inserate zählen.