<div class="statistik">
    <table class="table_statistik" cellpadding="3" summary="Zahlungen in den Bundesländern">
        <tr>
            <th class="label_region">Printmedium</th>
            <th class="label">Gesamt</th>
            <th class="label">Jan</th>
            <th class="label">Febr</th>
            <th class="label">März</th>
            <th class="label">Apr</th>
            <th class="label">Mai</th>
            <th class="label">Juni</th>
            <th class="label">Juli</th>
            <th class="label">Aug</th>
            <th class="label">Sept</th>
            <th class="label">Okt</th>
            <th class="label">Nov</th>
            <th class="label">Dez</th>
        </tr>
<?php foreach ($this->table['regions'] as $region) : ?>
        <tr>
            <td class="label_region"><?php echo $region['region'] ?></td>
            <td class="label"><?php echo number_format($this->table[$region['id_config']]['all'], 0, ',', '.') ?>.-</td>
<?php   for ($month = 1; $month <= 12; $month++) : ?>
            <td class="label"><?php echo number_format($this->table[$region['id_config']][$month], 0, ',', '.') ?>.-</td>
<?php   endfor ?>
        </tr>
<?php endforeach ?>
    </table>
</div>
Ausgaben in EUR. Nur zugeordnete Inserate zählen.
