<?php echo $this->doctype() ?> 
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php echo $this->headTitle()->setIndent(4) ?>

    <meta name="robots" content="index, follow" />
    <meta name="description" content="Polit-Inserate: Wir zahlen, sie werben." lang="de" />
    <meta name="keywords" content="Politik Regierung Partei Inserate Werbung Steuergeld" lang="de" />
<?php
echo $this->headLink()->setIndent(4);
echo $this->headMeta()->setIndent(4);
echo $this->headStyle()->setIndent(4);
?>
<?php 
if (Zend_Registry::get('PrintmediumTypes'))
    $this->dojo()->requireModule('dojo.parser');

if ($this->dojo()->isEnabled() && !Zend_Registry::get('StartPage'))
    echo $this->dojo();

?>

<script language="javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" type="text/javascript"></script>
</head>
<body class="body tundra"<?php if (Zend_Registry::get('PrintmediumTypes')) echo ' onload="UpdateFields();"' ?>>
<a href="http://github.com/gemane/politinserate"><img style="position: absolute; top: 0; left: 0; border: 0;" src="https://assets1.github.com/img/c641758e06304bc53ae7f633269018169e7e5851?repo=&url=http%3A%2F%2Fs3.amazonaws.com%2Fgithub%2Fribbons%2Fforkme_left_white_ffffff.png&path=" alt="Fork me on GitHub"></a>
<div class="layout_position layout_size" style="padding:0px;margin-bottom:15px;font-size:15px;">
<div class="links"><a href="/links">Partner</a> | <a href="http://blog.politinserate.at">Blog</a> | <a href="/faq">Hilfe</a></div>
<?php if (Zend_Registry::get('auth')->hasIdentity()) : ?>
<div class="login" style=""><a href="/user/profile/<?php echo Zend_Registry::get('auth')->getIdentity()->username ?>">Profil <?php echo Zend_Registry::get('auth')->getIdentity()->username ?></a> | 
<a href="/logout">Logout</a></div>
<?php else : ?>
<div class="login"><a href="/login">Login</a> | <a href="/user/register">Registrieren</a></div>
<?php endif ?>
</div>

<div class="layout_position layout_size layout_design" style="background-color: #FCFF98;border:1px solid black;padding-bottom:10px;margin-bottom:0px;">
<h1 id="header"><a href="/"><img src="/images/logo.png" width="217" height="52" alt="Logo:Polit-Inserate.at, Wir zahlen, sie werben." style="border:none;" /></a></h1>

<ul id="navigation" style="position:absolute; right:1em;">
    <li><a href="/eingabe/foto">Neues Inserat</a></li>
    <li><a href="/stream/tagged" onmouseover="showit(0)" onmouseout="resetit(event)">Inserate</a></li>
    <li><a href="/statistiken/parteien" onmouseover="showit(1)" onmouseout="resetit(event)">Statistiken</a></li>
    <li><a href="/tarife">Anzeigentarife</a></li>
</ul>
<div id="describe" onmouseover="clear_delayhide()" onmouseout="resetit(event)"></div>
</div>
<div class="layout_position layout_size layout_design" style="background-color:#646567;border:1px solid black;padding-top:5px;padding-bottom:5px;margin-bottom:0px;">
<span style="color:white;text-align:center;">Gesamtausgaben für Inseratschaltungen im System: <?php $this->formatCurrency(Zend_Registry::get('expense')) ?> (seit Mitte 2010)</span>
</div>
<?php if ('testing' == APPLICATION_ENV) : ?>
<div class="layout_position layout_size layout_design" style="background-color:red;border:1px solid black;padding-top:5px;padding-bottom:5px;margin-bottom:0px;">
<span style="color:white;text-align:center;">Testseite (Datenbank liegt auf einem freien Server)</span>
</div>
<?php endif ?>

<?php 
if (isset($this->ev))
    $this->writeError($this->ev);
?>
<div class="layout_position layout_size layout_design" >
<div style="width: 780px; float: left;">
<?php echo $this->layout()->content ?>
<?php echo $this->inlineScript() ?>
</div>

<!-- Sidebar start -->
<div style="width:210px;float:right; border-left: 1px dashed #191919;">

<div style="font-size: 70%; clear:both; ">
<div style="margin-left: 40px; width: 50px; float: left;line-height:100%;"><a style="text-decoration:none;" href="http://blog.politinserate.at/feed/" title="RSS-Abo der Blogbeiträge"><img style="border:none;" src="/images/rssfeedicon.jpg" height="35" width="35" alt="RSS-Abo starten" />&nbsp;RSS</a></div>
<div style="margin-left: 15px; width: 50px; float: left; line-height:100%;"><a style="text-decoration:none;" href="http://twitter.com/politinserate" title="@politinserate auf Twitter folgen"><img style="margin-left:3px; border:none;" src="/images/twitter.jpg" height="35" width="35" alt="@politinserate auf Twitter folgen" />Twitter</a></div>
</div>

<!--<div id="sidebar" style="padding: 10px 0px 0px 10px; clear:left;">
<iframe src="<?php //echo '/blog/sidebar.php'; ?>" width="210" height="250" scrolling="no" frameborder="0" margin="0"></iframe>
</div>-->

<div style="padding: 10px 0px 0px 10px; clear:left;">
<script type="text/javascript" src="http://widgets.twimg.com/j/2/widget.js"></script>
<script type="text/javascript">
new TWTR.Widget({
  version: 2,
  type: 'profile',
  rpp: 5,
  interval: 6000,
  width: 200,
  height: 250,
  theme: {
    shell: {
      background: '#F58E0E',
      color: '#ffffff'
    },
    tweets: {
      background: '#FCFF98',
      color: '#444444',
      links: '#852806'
    }
  },
  features: {
    scrollbar: true,
    loop: false,
    live: true,
    hashtags: true,
    timestamp: true,
    avatars: true,
    toptweets: true,
    behavior: 'all'
  }
}).render().setUser('politinserate').start();
</script>
</div>

<div style="padding: 10px 0px 0px 10px;"><script type="text/javascript" src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script><fb:like-box href="https://www.facebook.com/pages/Polit-Inserateat/141426775920579" width="200" show_faces="true" stream="false" header="true"></fb:like-box></div>

<div style="padding: 10px 0px 0px 10px;text-align:left;">Powered with<br />
<a href="http://framework.zend.com/"><img style="border:none;" src="/images/zf.png" width="122" height="24" /></a> <a href="http://dojotoolkit.org/"><img style="border:none;" src="/images/dojo.png" width="67" height="30" /></a></div>

</div>
<div style="clear:both;"></div>
<!-- Sidebar end -->

</div>
<div id="footer">
    <span style="">
        © <?php echo date('Y', time()) ?> Gerold Neuwirt | <a href="/datenschutz">Datenschutz</a> | <a href="/agb">AGBs</a> | <a href="/impressum">Impressum</a> | <a href="/kontakt">Kontakt</a>
    </span>
</div>

<?php 

if ($this->dojo()->isEnabled() && Zend_Registry::get('StartPage'))
    echo $this->dojo();

?>
<?php echo $this->headScript(); ?>

<!-- Feedback button -->
<!-- https://politinserate.uservoice.com/admin/dashboard -->
<script type="text/javascript">
var uservoiceOptions = {
  /* required */
  key: 'politinserate',
  host: 'politinserate.uservoice.com', 
  forum: '102641',
  showTab: true,  
  /* optional */
  alignment: 'left',
  background_color:'#f00', 
  text_color: 'white',
  hover_color: '#06C',
  lang: 'en'
};

function _loadUserVoice() {
  var s = document.createElement('script');
  s.setAttribute('type', 'text/javascript');
  s.setAttribute('src', ("https:" == document.location.protocol ? "https://" : "http://") + "cdn.uservoice.com/javascripts/widgets/tab.js");
  document.getElementsByTagName('head')[0].appendChild(s);
}
_loadSuper = window.onload;
window.onload = (typeof window.onload != 'function') ? _loadUserVoice : function() { _loadSuper(); _loadUserVoice(); };
</script>

</body>
</html>
