<?php echo $this->doctype() ?> 
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php echo $this->headTitle()->setIndent(4) ?>

    <meta name="robots" content="index, follow" />
    <meta name="description" content="Polit-Inserate: Wir zahlen, sie werben." lang="de" />
    <meta name="keywords" content="Politik Regierung Partei Inserate Werbung Steuergeld" lang="de" />
<?php
echo $this->headLink()->setIndent(4);
echo $this->headMeta()->setIndent(4);
echo $this->headStyle()->setIndent(4);
?>
    <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-18459406-1']);
        _gaq.push(['_trackPageview']);
        
        (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
    </script>
</head>
<body class="body"<?php if (Zend_Registry::get('PrintmediumTypes')) echo ' onload="UpdateFields();"' ?>>
<div class="layout_position layout_size_mobile" style="padding:0px; margin-bottom:15px; font-size:15px;">
<div class="links_mobile"><a href="/links">Partner</a> | <a href="http://blog.politinserate.at">Blog</a> | <a href="/faq">Hilfe</a> | 
<?php if (Zend_Registry::get('auth')->hasIdentity()) : ?>
<a href="/user/profile/<?php echo Zend_Registry::get('auth')->getIdentity()->username ?>">Profil <?php echo Zend_Registry::get('auth')->getIdentity()->username ?></a> | 
<a href="/logout">Logout</a>
<?php else : ?>
<a href="/login">Login</a> | <a href="/user/register">Registrieren</a>
<?php endif ?>
</div>
</div>

<div class="layout_position layout_size_mobile layout_design" style="background-color: #FCFF98;border:1px solid black;border-bottom:0px;padding-bottom:0px;margin-bottom:0px;">
<h1 id="header_mobile"><a href="/"><img src="/images/logo.png" width="217" height="52" alt="Logo:Polit-Inserate.at, Wir zahlen, sie werben." style="border:none;" /></a></h1>
</div>
<div class="layout_position layout_size_mobile layout_design" style="background-color: #FCFF98;border:1px solid black;border-top:0px; padding-bottom:60px;margin-bottom:0px;font-size: 80%;">
<ul id="navigation">
    <li><a href="/eingabe/foto">Neues Inserat</a></li>
    <li><a href="/stream/tagged" onmouseover="showit(0)" onmouseout="resetit(event)">Inserate</a></li>
    <li><a href="/statistiken/parteien" onmouseover="showit(1)" onmouseout="resetit(event)">Statistiken</a></li>
    <li><a href="/tarife">Anzeigentarife</a></li>
</ul>
<div id="describe" onmouseover="clear_delayhide()" onmouseout="resetit(event)"></div>
</div>
<div class="layout_position layout_size_mobile layout_design" style="background-color:#646567;border:1px solid black;padding-top:5px;padding-bottom:5px;margin-bottom:0px;">
<span style="color:white;text-align:center;">Gesamtausgaben für Inseratschaltungen im System: <?php $this->formatCurrency(Zend_Registry::get('expense')) ?> (seit Mitte 2010)</span>
</div>
<?php if ('testing' == APPLICATION_ENV) : ?>
<div class="layout_position layout_size_mobile layout_design" style="background-color:red;border:1px solid black;padding-top:5px;padding-bottom:5px;margin-bottom:0px;">
<span style="color:white;text-align:center;">Testseite (Datenbank liegt auf einem freien Server)</span>
</div>
<?php endif ?>

<?php 
if (isset($this->ev))
    $this->writeError($this->ev);
?>
<div class="layout_position layout_size_mobile layout_design" >
<?php echo $this->layout()->content ?>
<?php echo $this->inlineScript() ?>
<div style="clear:both;"></div>
</div>
<div id="footer">
    <span style="">
        © <?php echo date('Y', time()) ?> Gerold Neuwirt | <a href="/datenschutz">Datenschutz</a> | <a href="/agb">AGBs</a> | <a href="/impressum">Impressum</a> | <a href="/kontakt">Kontakt</a>
    </span>
</div>
<?php echo $this->headScript(); ?>

</body>
</html>
