<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Default Application</title>
</head>
<body>
  <h1>Ein Fehler ist aufgetreten</h1>
<br />
  <h3 style="text-align:center;">Bitte laden Sie die entsprechende Seite erneut.</h3>
  <p>
    Mögliche Ursache ist eine Zeitüberschreitung <br />oder das Laden der Seite aus dem Cache.
      <!--<b>Message:</b> Cross site forgery request (CSFR) detected.-->
  </p>


</body>
</html>
