<?php 
$this->headTitle()->append('Passwort Änderung');
$this->headScript()->appendScript('
function confirmPassword(value, constraints)
{
    var isValid = false;
    if(constraints && constraints.other)  {
        var otherInput =  dijit.byId(constraints.other);
        if(otherInput) {
                var otherValue = otherInput.value;
                console.log("%s == %s ?", value, otherValue);
                isValid = (value == otherValue);
        }
    }
    return isValid;
}
function onsubmit()
{
    var p1 = dijit.byId("newpassword1").value;
    var p2 = dijit.byId("newpassword2").value;
    return p1 == p2;
}
');

?>
<h2>Passwort Änderung</h2>
<?php if (!empty($this->message)) : ?>
<span class="errors"><?php   print_r($this->message) ?></span>
<?php endif ?>
<br />
<?php echo $this->formFixer($this->form) ?>
<div style="clear:both;">

</div>