<?php 
$this->headTitle()->append('Registrierung');
?>
<h2>Registrierung</h2>
<div style="width:500px;margin:auto;">
<p>Willkommen auf unserer Seite. Sie haben sich mit dem Benutzernamen "<?php echo $this->username ?>" registriert. </p>

<p>Wir haben Ihnen eine Email mit den Accountinformationen an die bei der Registrierung angegebene Emailadresse zugesendet. Bitte folgen Sie dem Aktivierungslink in der Nachricht, um die Registrierung abzuschließen.</p>
<p>Wenn die Aktivierung nicht innerhalb von 7 Tagen erfolgt, wird diese Registrierung gelöscht.</p>
</div>
