<?php 
$this->headTitle()->append('Login');
?>
<h2>Login</h2>
<?php if (!empty($this->message)) : ?>
<span class="errors"><?php   print_r($this->message) ?></span>
<br />
<?php endif ?>
<br />
<?php echo $this->formFixer($this->form) ?>
<div style="clear:both;">
Du hast dich noch nicht registriert?<br />
Registrier dich <a href="/user/register">hier</a>.<br />
<span style="font-size:80%;"><a href="/user/lostpassword">Passwort vergessen?</a></span>
</div>

<script type="text/javascript">
    document.getElementById("return_link").value = document.referrer;
</script>
