<?php 
$this->headTitle()->append('Passwort vergessen');
?>
<h2>Passwort vergessen</h2>
<?php if (!empty($this->message)) : ?>
<span class="errors"><?php   print_r($this->message) ?></span>
<br /><br />
<?php else : ?>
<p class="errors" style="font-size:14px; width:300px;text-align:center;margin:0 auto;padding-bottom:20px;">Eine Email mit einem neuen Passwort wird an die Emailadresse gesendet.</p>
<?php endif ?>
<?php echo $this->formFixer($this->form) ?>
