<?php 
$this->headTitle()->append('Profil');
?>
<h2>Profil von <?php echo $this->username ?></h2>
<h3>Benutzerseite</h3>
<a href="/<?php echo $this->username ?>">Zugeordnete Inserate</a>
<br /><br />
<hr />
<h3>Aktivitäten</h3>
<ul style="list-style-type: none;">
<li>Fotos hochgeladen: <?php echo $this->numPhotos ?></li>
<li>Inserate zugeordnet: <?php echo $this->numInserate ?></li>
</ul>
<hr />
<h3>Einstellungen</h3>
<p>Folgende Einstellungen werden beim Eintragen<br /> von neuen Inseraten berücksichtigt:</p>
<?php if (!empty($this->message)) : ?>
<span class="errors"><?php   print_r($this->message) ?></span>
<?php endif ?>
<?php echo $this->formFixer($this->form) ?>
<div style="clear:both;">
<!--TODO2 Benachrichtigung über neue hochgeladenen Inseraten-->
</div>