<div class="">

<div style="font-size:20px;text-decoration: none;border: 1px solid #AAA; padding:5px;margin:0 auto;width:350px; -moz-border-radius: 7px; -webkit-border-radius: 7px; border-radius:7px; background: url(/images/button_grey.png) 0 0 repeat-x;">
Jahr: 
<?php for ($year = $this->year_from; $year <= $this->year_to; $year++) : if ($year == $this->year) : ?>
    <strong><?php echo $this->year ?></strong>
<?php   elseif (false == array_key_exists($year, $this->list)) : ?>
    <?php echo $year ?>
<?php   else : ?>
    <a href="<?php echo $this->url . '/year/' . $year . '/month/' . $this->month ?>" style="text-decoration: none;"><?php echo $year ?></a>
<?php   endif; endfor ?>
<br />
Monat: 
<?php for ($month = 1; $month <= 12; $month++) : if ($month == $this->month) : ?>
    <strong><?php echo $this->month ?></strong>
<?php   elseif (false == in_array($month, $this->list[$this->year])) : ?>
    <?php echo $month ?>
<?php   else : ?>
    <a href="<?php echo $this->url . '/year/' . $this->year . '/month/' . $month ?>" style="text-decoration: none;"><?php echo $month ?></a>
<?php endif; endfor ?>
</div>
</div>
